model_name: VideoMambaPose
# heatmap project directory
project_dir: /home/linxin67/projects/def-btaati/linxin67/Projects/MambaPose/Video_Pose/3_VideoMambaPose/src/models/experiments/heatmap/

model_type: 'Heatmap_2d_deconv_linear_regression'

# full_debug mode will enable a lot of information being printed
full_debug: False

# architecture mamba
embed_channels: 192 # number of channels after the tiny mamba layers.
num_mamba_blocks: 12

# deconv
num_deconv: 2
2d_deconv: True
deconv_channels: 192
  # using 2d or 3d deconvolutions
num_conv: 2
conv_channels: 256
joint_regressor: True
  # joint regressor
hidden_channels: 512
output_dimensions: 2 # x, y
dropout: False
dropout_percent: 0.25 # if dropout is True

# training
epoch_number: 300
# batch_size: 16
# batch_size: 8
batch_size: 16 # just to see how scalable it is
# learning_rate: 0.001
learning_rate: 0.01
#scheduler:
scheduler: True
start_epoch: 1

# device settings
  # (should be changed depending on the model)
num_cpus: 1
num_gpus: 1
parallelize: False

# checkpoints
checkpoint_directory: /home/linxin67/projects/def-btaati/linxin67/Projects/MambaPose/Video_Pose/3_VideoMambaPose/src/models/experiments/heatmap/checkpoint
# checkpoint_name: 'Custom_Tanh_normalized_checkpoints'
checkpoint_name: 'New_LR_Custom_Tanh_normalized_checkpoints'
# checkpoint_name: 'testing_false_dataset'

# Follow up on the training of another previous run?
follow_up: False

  # if yes
previous_training_epoch: 1
previous_checkpoint: ''

# data
dataset_name: 'JHMDB'
data_path: /home/linxin67/scratch/JHMDB
annotations_path: /home/linxin67/scratch/JHMDB_old/annotations
# use avi videos
use_videos: True
# actions to skip
skip: ['wave']
num_frames: 16
# RGB
channels: 3
image_height: 240
image_width: 320
image_tensor_height: 192 
image_tensor_width: 256
patch_number: 192 # number of patches, each of size 4 pixels by 4 pixels
patch_size: 16 # each patch is 4x4
jump: 1 # number of frames to skip between the different datapoints
joint_number: 15

# if False, uses subset of the data to run
real_job: True

# normalization
normalized: True
default: False # not the default normalization

